name = "MunchCraft"
author = "Adrian Vecina"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f61d115bd09e08baa1e24201590d300e3dbba3d74f0f33a60aca8e1614a58fc"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
