name = "MunchCrfaft"
author = "Adrian Vecina"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99040128c1da72c8143316bd484b5f44caa457ad30fbc14cb8a165c68cd71445"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
