name = "MunchCrfaft"
author = "Adrian Vecina"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e93571a22f39bb3cc8e6cb8fd406b988b6ff0952aab562bffaa15333819b3a5"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
