name = "MunchCraft"
author = "Adrian Vecina"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf3e32791227d845f4adb7058ef9769c06f015459426e251b33b7a3b004ef7aa"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
