name = "MunchCraft"
author = "Adrian Vecina"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5e121bd79148a5a846985b005f951420d196c9469ce7088ce2f07f41557a2f0"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
