name = "MunchCraft"
author = "Adrian Vecina"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a5cca62a231dabcfe178a1a9e97efd9845a126910b07a59c49b1dddbb43b864"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
