name = "MunchCraft"
author = "Adrian Vecina"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40d4d633e857a2cf2618e0310e5a2d86972bb7baf5e5cb454d069cbbb32bd324"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
