name = "MunchCrfaft"
author = "Adrian Vecina"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6beede6e12f3178bc6c8faf37ef9b91d652d66212d83766c1924470aa9f5dd8b"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
